### ISSUE TITLE
Are you able to write up your install "integration" process a bit?

### ISSUE THREAD

**Issue by roni-estein** [francescomalatesta/laravel-api-boilerplate-jwt#18]
This works like a charm, however, getting this to work on a larger laravel 5.1 project has been pretty painful. It would be awesome if there was a corresponding bit of setup documentation of what you did for those who don't have the depth of laravel.

For example the boilerplate file was very enlightening, and adding an alternate routes file was also a great concept.

It would be nice to be able to configure this startup API into an existing project.

Thanks,

-Roni

**Comment by francescomalatesta** [comment]
I already wrote a couple of tutorials on this package on Sitepoint, I just added them to the readme file.

Closing because of [https://github.com/francescomalatesta/laravel-api-boilerplate-jwt/commit/2758234e01e60abfc1d7a133b8b76badf6870810](https://github.com/francescomalatesta/laravel-api-boilerplate-jwt/commit/2758234e01e60abfc1d7a133b8b76badf6870810)
